---
- hosts: rasp
  become: true
  tasks:

    - name: Ping the Raspberry Pi
      ansible.builtin.ping:

    - name: Check the uptime of the Raspberry Pi
      ansible.builtin.command:
        cmd: uptime
      register: uptime_result

    - name: Display uptime
      ansible.builtin.debug:
        msg: "Uptime: {{ uptime_result.stdout }}"
